### ISSUE TITLE
Save more informations

### ISSUE THREAD

**Issue by yvesnetalis** [dmcbrn/laravel-email-database-log#4]
Hello, Thank you for this project. Do you have a proposal to record additional information when logging a message. For example, I would like to add a column "customer_id" to find all the mails sent to a customer. Thanks

**Comment by dmcbrn** [comment]
Thanks, and sorry for the late reply.

Best way to do this (as far as I can see) would be to create a "pivot" table and connect the emails to whatever other table/model through that pivot table.

Otherwise I'd need to add another column for each request I get here and the library would quickly become a mess with bunch of columns that 99% users wont use.

I could generate an [Laravel Event](https://laravel.com/docs/5.8/events) whenever the email is logged and then you could hook up to it by a listener. Does that seems like a reasonable approach?

Any suggestion or an idea for a different approach is highly appreciated.

**Comment by dmcbrn** [comment]
@yvesnetalis 

Can you please try v2.2.4?
Check the readme for more info on implementation please.

**Comment by yvesnetalis** [comment]
Thank you for your answer and this new version

Laravel Event are probably a good idea but I dont know how to use them for my case

That's for now what I did (it's a little "dirty" and it's not the exact code)

In a Controller, I call Mailable

```php
Mail::to($customeruser->email)->send(new ToCustomerMailer($invoice);
```

In the _build_ method of the Mailable, I inject headers with Swift

```php
    public function build()
    {

        $this->withSwiftMessage(function ($message) { // ajouter les infos
                $headers->addTextHeader('MY_INFO', 'TEST');
        });

        return $this->replyTo(env('MAIL_FROM_ADDRESS'))
                    ->subject('test')
                    ->attach($this->invoice->getPdf(), [
                        'as' => $this->invoice->pdf_filename,
                        'mime' => 'application/pdf',
                    ])
                    ->markdown('emails.admin.invoice.invoice.to_customer_mailer');
    }
```
More dirty after :wink:  . I changed your EmailLogger class

```php
        $emailLog = EmailLog::create([
            'date' => date('Y-m-d H:i:s'),
            'from' => $this->formatAddressField($message, 'From'),
            'to' => $this->formatAddressField($message, 'To'),
            'cc' => $this->formatAddressField($message, 'Cc'),
            'bcc' => $this->formatAddressField($message, 'Bcc'),
            'subject' => $message->getSubject(),
            'body' => $message->getBody(),
            'headers' => (string)$message->getHeaders(),
            'attachments' => empty($attachments) ? null : implode(', ', $attachments),
            'messageId' => $messageId,
            'mail_driver' => config('mail.driver'),
            'MY_INFO' => $message->getHeaders()->get('MY_INFO')->getFieldBody();
        ]);
```
And I changed EmailLog model $fillable to add MY_INFO field...

Feel free to suggest other idea

I will think about other solutions...

**Comment by dmcbrn** [comment]
You should create a separate model. Let's call it `EmailLoggerExtraInformation`.

Add to it fields that you need. For simplicity I'll just add the necessary two:

* `my_info` - let's say this is a text input which you can parse after or use multiple columns
* `message_id` - this is the key to relate this new model to the EmailLog model, it references `id` column on `email_log` table

So this new model will `belong_to` EmailLog model.

Then you create a Laravel Listener. I don't know by heart how to do it but I've done it many times and it should be simple. If I recall it right: create folder `Listeners` in your `app` folder, then add a Class to the folder (there should be sample in the docs for the Listener Class), then register the event/listener in `app/Providers/EventServiceProvider.php` (I think), be sure to connect the listener to the Event I've added in v2.2.4. That should be it.

Then in that Listener you put your logic. In this example it should be to create new instance of `EmailLoggerExtraInformation` and save it.

It's not as pretty as your solution but if you do it like you've done it you'll have to update the code every time you install or update the library. 

Hope it all makes sense. I'm still not 100% sure are you having problems with Laravel Events/Listeners or something else.

Please note, I did not test this :(

**Comment by kentdahl** [comment]
Note that since the mails are logged to a database with Eloquent, its events are triggered and can be used directly. No need to create separate events to make it work, although it makes for a cleaner API. 

I ended up using the Eloquent 'created' event from `EmailLogEvent` to get my app to respond when an email was logged.

Very briefly put;

```php
<?php
namespace App\Observers;
use Dmcbrn\LaravelEmailDatabaseLog\EmailLogEvent;
class MailLogEventObserver
{
    public function created(EmailLogEvent $emailLogEvent)
    {
        $mgEventType = $emailLogEvent->event;
        switch ($mgEventType) {
            case "rejected":
            case "failed":
                $this->sendWarningEmailToUser($emailLogEvent);
                break;
            default:
                return null;
        }
    }
[....]
```

Hooked up in EventServiceProvider.php in the boot method.

```php
<?php
namespace App\Providers;
use Illuminate\Foundation\Support\Providers\EventServiceProvider as ServiceProvider;
use App\Observers\MailLogEventObserver;
use Dmcbrn\LaravelEmailDatabaseLog\EmailLogEvent;
class EventServiceProvider extends ServiceProvider
{
  [...]
    public function boot()
    {
        parent::boot();
        EmailLogEvent::observe(MailLogEventObserver::class);
    }
}
```

**Comment by dmcbrn** [comment]
I think this can be closed. Feel free to reopen if needed.
