### ISSUE TITLE
Support for Laravel 6 - PR #6

### ISSUE THREAD

**Issue by xitude** [dmcbrn/laravel-email-database-log#7]
Could you please review pr #6 for support for laravel 6

**Comment by dmcbrn** [comment]
Sorry I'm really busy and will be for the following months. I suggest you fork it for now and I'll comment here if I have time to do some work on the library.

Related to topic: I think your PR would make it not work on lower versions on Laravel, no?
I need to research into these composer dependencies a bit.

Once again, really sorry for the very late reply.

**Comment by dmcbrn** [comment]
Merged.
For 6.0 in composer require version `3.0`
